services:
    _defaults:
        autowire: true
        autoconfigure: true

    BytesCommerce\Zabbix\ZabbixClientInterface:
        class: BytesCommerce\Zabbix\ZabbixClient
        arguments:
            $cache: '@cache.app'
            $username: '%zabbix_api.username%'
            $password: '%zabbix_api.password%'
            $authTtl: '%zabbix_api.auth_ttl%'

    BytesCommerce\Zabbix\ZabbixServiceInterface:
        class: BytesCommerce\Zabbix\ZabbixService

    BytesCommerce\Zabbix\ActionServiceInterface:
        class: BytesCommerce\Zabbix\ActionService
