# yaml-language-server: $schema=../../../vendor/symfony/dependency-injection/Loader/schema/services.schema.json
services:
    _defaults:
        autowire: true
        autoconfigure: true

    BytesCommerce\ZabbixApi\ZabbixClientInterface:
        class: BytesCommerce\ZabbixApi\ZabbixClient
        arguments:
            $cache: '@cache.app'
            $username: '%zabbix_api.username%'
            $password: '%zabbix_api.password%'
            $authTtl: '%zabbix_api.auth_ttl%'

    BytesCommerce\ZabbixApi\ZabbixServiceInterface:
        class: BytesCommerce\ZabbixApi\ZabbixService

    BytesCommerce\ZabbixApi\ActionServiceInterface:
        class: BytesCommerce\ZabbixApi\ActionService
